import React, { FC } from 'react'
// src
import style from './Main.module.scss'
const Main: FC = () => {
  return (
        <div className={style['main__container']}>

            <div>
                <h2 id={'На цьому сайті ви дізнаєтесь про'}>На цьому сайті ви дізнаєтесь про</h2>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
            </div>
            <div>

                <h2 id={'Here you can read about ...'}> Here you can read about ...  </h2>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?

            </div>
            <div>
                <h3 id={'Title3'}>Title3  </h3>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet aut beatae dolor dolore dolores ducimus earum eligendi eveniet expedita fugiat illo impedit inventore iure molestiae nam natus necessitatibus neque nesciunt nisi nostrum nulla officia pariatur possimus provident quam quibusdam quidem quisquam reiciendis, repellat sapiente sint sunt ullam unde ut voluptate voluptatibus. Ad et expedita numquam optio perspiciatis repellat. A assumenda cupiditate excepturi facere hic iusto laboriosam laborum maxime molestias quos, soluta voluptatibus. Adipisci aliquid amet architecto, asperiores assumenda atque consectetur corporis dignissimos dolor dolores error excepturi fugiat ipsam molestiae mollitia numquam rem, repellat sequi suscipit tenetur. Consequatur, ipsum, odit?

            </div>
            <div className={style['main__posts_container']}>

            </div>

        </div>
  )
}

export { Main }
